---
all:
  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_user: "root"

  hosts:
    test-debian11:
      ansible_host: 192.168.0.12

  children:
    test_new:
      hosts:
        test-debian11:
    test_servers:
      children:
        test_new:
